version: "3.9"
services:
  postgres:
    image: postgres:15-bullseye
    environment:
      POSTGRES_DB: "karamel"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - /postgresql:/var/lib/postgresql
    ports:
      - "5433:5432"