server:
  port: ${APP_PORT}

robokassa:
  id-url: https://auth.robokassa.ru/Merchant/Indexjson.aspx
  invoice-url: https://auth.robokassa.ru/Merchant/Index/
  invoice-status: https://auth.robokassa.ru/Merchant/WebService/Service.asmx/OpStateExt?

spring:
  mail:
    host: smtp.yandex.ru
    port: 465
    username: caramel.kras@yandex.ru
    password: zfmuynwokohwkfwe
    properties:
      mail:
        smtp:
          auth: true
          ssl.enable: true
  flyway:
    baselineOnMigrate: true
    enabled: true
  banner:
    location: banner.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/karamel
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true
  city-info:
    msko:
      city-name: МОСКВА
      bitrix-field-num: 87
      start-endpoint: 2024-11-29T00:00:00+00:00
      finish-endpoint: 2024-12-29T00:00:00+00:00
      address: Московская область, Красногорск, Причальная 82,
      manager-contact-numbers:
        - +7 (499) 113-05-59
      vk-link: https://vk.com/carameldm
      offer-link: https://карамельнаяфабрика.рф/oferta_msk
      payment-info:
        robokassa-pass1: ${PASS1:InSao1bBOvL7j0v9P9sI}
        robokassa-pass2: ${PASS2:uN1BeWTT9aMT9o5US7ZB}
        robokassa-pass1-test: ${PASS1-TEST:By8iawkcPI48B1QveQw3}
        robokassa-pass2-test: ${PASS1-TEST:n1Dojs8v45dearGwXa5h}
        login: ${LOGIN:Karamel_Msk}
        sno: osn
        tax: none
    mskm:
      city-name: МОСКВА
      bitrix-field-num: 87
      start-endpoint: 2024-11-29T00:00:00+00:00
      finish-endpoint: 2024-12-29T00:00:00+00:00
      address: Московская область, Мытищи, мкр. Олимпийский, ул. Щорса, 34
      manager-contact-numbers:
        - +7 (499) 113-05-59
      vk-link: https://vk.com/carameldm
      offer-link: https://карамельнаяфабрика.рф/oferta_msk
      payment-info:
        robokassa-pass1: ${PASS1:InSao1bBOvL7j0v9P9sI}
        robokassa-pass2: ${PASS2:uN1BeWTT9aMT9o5US7ZB}
        robokassa-pass1-test: ${PASS1-TEST:By8iawkcPI48B1QveQw3}
        robokassa-pass2-test: ${PASS1-TEST:n1Dojs8v45dearGwXa5h}
        login: ${LOGIN:Karamel_Msk}
        sno: osn
        tax: none
    chel:
      city-name: ЧЕЛЯБИНСК
      bitrix-field-num: 89
      start-endpoint: 2024-11-28T00:00:00+00:00
      finish-endpoint: 2025-01-07T00:00:00+00:00
      address: г. Челябинск, ул. Рощинская, дом 2
      manager-contact-numbers:
        - +7 (958) 756-98-49
      vk-link: https://vk.com/public222553186
      offer-link: https://карамельнаяфабрика.рф/oferta_chel
      payment-info:
        robokassa-pass1: ${PASS1:RKUWpV99v0u5uz9PHDgu}
        robokassa-pass2: ${PASS2:Q9tPg8uPf14x9TAKmWxM}
        robokassa-pass1-test: ${PASS1-TEST:ufoPT3nRN4jK3s1WQEp9}
        robokassa-pass2-test: ${PASS1-TEST:bjQqhwg5y8dk13zkGe9O}
        login: ${LOGIN:KaramelSamara}
        sno: osn
        tax: none
    tyumen:
      city-name: ТЮМЕНЬ
      bitrix-field-num: 91
      start-endpoint: 2024-11-29T00:00:00+00:00
      finish-endpoint: 2024-12-29T00:00:00+00:00
      address: Тюменская область, Тюменский район, посёлок Боровский, ул. Трактовая, д. 50/1 (дом 300 м.кв.)
      manager-contact-numbers:
        - +7 (958) 756-98-49
      vk-link: https://vk.com/public222553329
      offer-link: https://карамельнаяфабрика.рф/oferta_tumen
      payment-info:
        robokassa-pass1: ${PASS1:vrf0QXG65mM2ZA4WeiNm}
        robokassa-pass2: ${PASS2:itfI5djfH33sEVe1gn3V}
        robokassa-pass1-test: ${PASS1-TEST:Gn4aTHZ3qYVOfR40LXb7}
        robokassa-pass2-test: ${PASS1-TEST:nbZM43H0VPqqPsg84FpV}
        login: ${LOGIN:Karamel_Tumen2}
        sno: osn
        tax: none
    samara:
      city-name: САМАРА
      bitrix-field-num: 217
      start-endpoint: 2024-11-28T00:00:00+00:00
      finish-endpoint: 2025-01-07T00:00:00+00:00
      address: г. Самара, Красноглинский район, п. Красная Глинка, ул. Южная, д. 16
      manager-contact-numbers:
        - +7 (924) 914-84-23
      vk-link: https://vk.com/public222553152?ysclid=lo2v8ic1nb537889983
      offer-link: https://карамельнаяфабрика.рф/oferta_samara
      payment-info:
        robokassa-pass1: ${PASS1:X2zJxbAB5VYmb0u9vG3F}
        robokassa-pass2: ${PASS2:nCOOnrZIb0n3C0gw5x5y}
        robokassa-pass1-test: ${PASS1-TEST:j8Y6N9F3C8tWfHMVAkVF}
        robokassa-pass2-test: ${PASS1-TEST:Csad6E6Y4yU9gUVue6Bn}
        login: ${LOGIN:Karamel_Samara2}
        sno: osn
        tax: none