
spring:
  banner:
    location: banner.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/karamel
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true

    city-info:
      current-city: ${CURRENT_CITY:CHEL}
      chel:
        city-name: ?????????
        timezone: 3
        invoice-lifetime-minutes: 15
        start-endpoint: 2023-11-30T00:00:00+00:00
        finish-endpoint: 2024-01-10T00:00:00+00:00
        address: ??????????? ???????, ?????????? ?????, ???. ???????, ??. ?????????, ?.12
        manager-contact-numbers:
          - +79587569849
        vk-link: https://vk.com/public222553186
        offer-link: https://??????????????????.??/oferta_chel
        reservation-payment-amount: 5000
        maxCapacity: 36
        minCapacity: 20
        refundPeriod: 14
      ekb:
        city-name: ????????????
        timezone: 3
        invoice-lifetime-minutes: 15
        start-endpoint: 2023-11-30T00:00:00+00:00
        finish-endpoint: 2024-01-10T00:00:00+00:00
        address: ???????????? ???????, ?. ??????? ?????, ??. ?????????, ?.15 (??? 400 ?.??.)
        manager-contact-numbers:
          - +73432264525
          - +79952228767
        vk-link: https://vk.com/public222552916
        offer-link: https://??????????????????.??/oferta_ekat
        reservation-payment-amount: 5000
        maxCapacity: 36
        minCapacity: 20
      tyumen:
        city-name: ??????
        timezone: 3
        invoice-lifetime-minutes: 15
        start-endpoint: 2023-11-30T00:00:00+00:00
        finish-endpoint: 2024-01-10T00:00:00+00:00
        address: ????????? ???????, ????????? ?????, ??????? ?????????, ??. ?????????, ?. 50/1 (??? 300 ?.??.)
        manager-contact-numbers:
          - +73452518032
        vk-link: https://vk.com/public222553329
        offer-link: https://??????????????????.??/oferta_tumen
        reservation-payment-amount: 5000
        maxCapacity: 36
        minCapacity: 20
      izh:
        city-name: ??????
        timezone: 4
        invoice-lifetime-minutes: 15
        start-endpoint: 2023-11-30T00:00:00+00:00
        finish-endpoint: 2024-01-10T00:00:00+00:00
        address: ?. ??????, ?????????? ??????????, ??????????????? ?????, 4
        manager-contact-numbers:
          - +73412650630
          - +79952229680
        vk-link: https://vk.com/public222343940
        offer-link: https://??????????????????.??/oferta_izhevsk
        reservation-payment-amount: 5000
        maxCapacity: 36
        minCapacity: 18
      kras:
        city-name: ??????????
        timezone: 7
        invoice-lifetime-minutes: 15
        start-endpoint: 2023-11-30T00:00:00+00:00
        finish-endpoint: 2024-01-10T00:00:00+00:00
        address: ?. ??????????, ??. ??????????, ?. 24
        manager-contact-numbers:
          - +73919897947
          - +79952226742
        vk-link: https://vk.com/fabrikadmkrsn
        reservation-payment-amount: 5000
        offer-link: https://??????????????????.??/oferta_kras
        maxCapacity: 36
        minCapacity: 18
      nsk:
        city-name: ???????????
        timezone: 7
        invoice-lifetime-minutes: 15
        start-endpoint: 2023-11-30T00:00:00+00:00
        finish-endpoint: 2024-01-10T00:00:00+00:00
        address: ?. ???, ??. ??????????, ?. 27
        manager-contact-numbers:
          - +79952229459
          - +73832427074
        vk-link: https://vk.com/karameldmnovosib
        reservation-payment-amount: 5000
        offer-link: https://??????????????????.??/oferta_nov
        maxCapacity: 36
        minCapacity: 18
      samara:
        city-name: ??????
        timezone: 3
        invoice-lifetime-minutes: 15
        start-endpoint: 2023-11-30T00:00:00+00:00
        finish-endpoint: 2024-01-10T00:00:00+00:00
        address: ?. ??????, ?????????????? ?????, ?. ??????? ??????, ??. ?????, ?. 16
        manager-contact-numbers:
          - +79249148423
        vk-link: https://vk.com/public222553152?ysclid=lo2v8ic1nb537889983
        offer-link: https://??????????????????.??/oferta_samara
        reservation-payment-amount: 5000
        maxCapacity: 36
        minCapacity: 20
        refundPeriod: 14
      volgograd:
        city-name: ?????????
        timezone: 3
        invoice-lifetime-minutes: 15
        start-endpoint: 2023-11-30T00:00:00+00:00
        finish-endpoint: 2024-01-10T00:00:00+00:00
        address: ?????????, ??. ????????? ????????, ?.65
        manager-contact-numbers:
          - +79249145265
        vk-link: https://vk.com/public222553352
        offer-link: https://??????????????????.??/oferta_volga
        reservation-payment-amount: 5000
        maxCapacity: 36
        minCapacity: 20
        refundPeriod: 14
      lipetsk:
        city-name: ??????
        timezone: 3
        invoice-lifetime-minutes: 15
        start-endpoint: 2023-11-30T00:00:00+00:00
        finish-endpoint: 2024-01-10T00:00:00+00:00
        address: ???????? ???????, ???????? ?????, ???? ??????, ??. ????????, 6
        manager-contact-numbers:
          - +79249141709
        vk-link: https://vk.com/public222554035
        offer-link: https://??????????????????.??/oferta_lipetsk
        reservation-payment-amount: 5000
        maxCapacity: 36
        minCapacity: 20
        refundPeriod: 14
      perm:
        city-name: ?????
        timezone: 3
        invoice-lifetime-minutes: 15
        start-endpoint: 2023-11-30T00:00:00+00:00
        finish-endpoint: 2024-01-10T00:00:00+00:00
        address: ?. ?????, ??. ???????, ?. 3?
        manager-contact-numbers:
          - +79249141709
        vk-link: https://vk.com/public222554023
        offer-link: https://??????????????????.??/oferta_perm
        reservation-payment-amount: 5000
        maxCapacity: 36
        minCapacity: 20
        refundPeriod: 14
      spb:
        city-name: ?????-?????????
        timezone: 3
        invoice-lifetime-minutes: 15
        start-endpoint: 2023-11-30T00:00:00+00:00
        finish-endpoint: 2024-01-10T00:00:00+00:00
        address: ?. ?????-?????????, ???. ????????, ??. ????????????, ?. 17, ????? ?
        manager-contact-numbers:
          - +78125092995
          - +79699669259
        vk-link: https://vk.com/public222337083
        offer-link: https://??????????????????.??/oferta_spb
        reservation-payment-amount: 5000
        maxCapacity: 36
        minCapacity: 18
        refundPeriod: 7
      yar:
        city-name: ?????????
        timezone: 3
        invoice-lifetime-minutes: 15
        start-endpoint: 2023-11-30T00:00:00+00:00
        finish-endpoint: 2024-01-10T00:00:00+00:00
        address: ?. ?????????, ??????? ?????????, 4-? ????????? ?????, 16
        manager-contact-numbers:
          - +74852607104
          - +79675559726
        vk-link: https://vk.com/public222343606
        offer-link: https://??????????????????.??/oferta_yarosl
        reservation-payment-amount: 5000
        maxCapacity: 36
        minCapacity: 18
server:
  port: ${APP_PORT:8090}






